//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetProjects.PrintEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetProjects.PrintEngine.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string AbortButtonCaption {
            get {
                return ResourceManager.GetString("AbortButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aborting. Please wait... 的本地化字符串。
        /// </summary>
        public static string AbortingMessage {
            get {
                return ResourceManager.GetString("AbortingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ActiveSlideToolTip {
            get {
                return ResourceManager.GetString("ActiveSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Payment Transaction 的本地化字符串。
        /// </summary>
        public static string AddPTTooltip {
            get {
                return ResourceManager.GetString("AddPTTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Slide 的本地化字符串。
        /// </summary>
        public static string AddSlideButtonCaption {
            get {
                return ResourceManager.GetString("AddSlideButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Slide 的本地化字符串。
        /// </summary>
        public static string AddSlideToolTip {
            get {
                return ResourceManager.GetString("AddSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Bottom 的本地化字符串。
        /// </summary>
        public static string AlignBottomToolTip {
            get {
                return ResourceManager.GetString("AlignBottomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Center 的本地化字符串。
        /// </summary>
        public static string AlignCenterTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("AlignCenterTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Center 的本地化字符串。
        /// </summary>
        public static string AlignCenterToolTip {
            get {
                return ResourceManager.GetString("AlignCenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        public static string AlignLeftNodePlacerToolTip {
            get {
                return ResourceManager.GetString("AlignLeftNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        public static string AlignLeftTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("AlignLeftTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        public static string AlignLeftToolTip {
            get {
                return ResourceManager.GetString("AlignLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Middle 的本地化字符串。
        /// </summary>
        public static string AlignMiddleToolTip {
            get {
                return ResourceManager.GetString("AlignMiddleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align/Resize Properties 的本地化字符串。
        /// </summary>
        public static string AlignResizeToolTip {
            get {
                return ResourceManager.GetString("AlignResizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Right 的本地化字符串。
        /// </summary>
        public static string AlignRightTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("AlignRightTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Right 的本地化字符串。
        /// </summary>
        public static string AlignRightToolTip {
            get {
                return ResourceManager.GetString("AlignRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Top 的本地化字符串。
        /// </summary>
        public static string AlignTopToolTip {
            get {
                return ResourceManager.GetString("AlignTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find a summary of key anti-avoidance information of each country 的本地化字符串。
        /// </summary>
        public static string AntiAvoidanceDescription {
            get {
                return ResourceManager.GetString("AntiAvoidanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-Avoidance 的本地化字符串。
        /// </summary>
        public static string AntiAvoidanceHeader {
            get {
                return ResourceManager.GetString("AntiAvoidanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select what you want to print 的本地化字符串。
        /// </summary>
        public static string AntiAvoidancePrintSelectionHeader {
            get {
                return ResourceManager.GetString("AntiAvoidancePrintSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string ApplyButtonCaption {
            get {
                return ResourceManager.GetString("ApplyButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to all entities 的本地化字符串。
        /// </summary>
        public static string ApplyToAllCheckBoxCaption {
            get {
                return ResourceManager.GetString("ApplyToAllCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to current items 的本地化字符串。
        /// </summary>
        public static string ApplyToCurrentItems {
            get {
                return ResourceManager.GetString("ApplyToCurrentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arc 的本地化字符串。
        /// </summary>
        public static string ArcToolTip {
            get {
                return ResourceManager.GetString("ArcToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both Filled 的本地化字符串。
        /// </summary>
        public static string ArrowHeadBothFillToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadBothFillToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both 的本地化字符串。
        /// </summary>
        public static string ArrowHeadBothToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadBothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Filled 的本地化字符串。
        /// </summary>
        public static string ArrowHeadLeftFillToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadLeftFillToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string ArrowHeadLeftToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string ArrowHeadNoneToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadNoneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Filled 的本地化字符串。
        /// </summary>
        public static string ArrowHeadRightFillToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadRightFillToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string ArrowHeadRightToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrow 的本地化字符串。
        /// </summary>
        public static string ArrowLineToolTip {
            get {
                return ResourceManager.GetString("ArrowLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrow 的本地化字符串。
        /// </summary>
        public static string ArrowToolTip {
            get {
                return ResourceManager.GetString("ArrowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Arrange On/Off 的本地化字符串。
        /// </summary>
        public static string AutoArrangeToolTip {
            get {
                return ResourceManager.GetString("AutoArrangeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balloon Tree Arc Layout 的本地化字符串。
        /// </summary>
        public static string BalloonTreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("BalloonTreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balloon Tree Layout 的本地化字符串。
        /// </summary>
        public static string BalloonTreeLayoutToolTip {
            get {
                return ResourceManager.GetString("BalloonTreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        public static string BoldToolTip {
            get {
                return ResourceManager.GetString("BoldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border Color 的本地化字符串。
        /// </summary>
        public static string BorderColorToolTip {
            get {
                return ResourceManager.GetString("BorderColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch must have a parent 的本地化字符串。
        /// </summary>
        public static string BranchMastHaveAParent {
            get {
                return ResourceManager.GetString("BranchMastHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch or Individual 的本地化字符串。
        /// </summary>
        public static string BranchToolTip {
            get {
                return ResourceManager.GetString("BranchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bullets 的本地化字符串。
        /// </summary>
        public static string BulletsTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("BulletsTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calendar Item 的本地化字符串。
        /// </summary>
        public static string CalendarMonthViewEditorTitle {
            get {
                return ResourceManager.GetString("CalendarMonthViewEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelButtonCaption {
            get {
                return ResourceManager.GetString("CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string CenterNodePlacerToolTip {
            get {
                return ResourceManager.GetString("CenterNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        public static string ChangeButtonCaption {
            get {
                return ResourceManager.GetString("ChangeButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Slide 的本地化字符串。
        /// </summary>
        public static string ChangeSlideButtonCaption {
            get {
                return ResourceManager.GetString("ChangeSlideButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Slide 的本地化字符串。
        /// </summary>
        public static string ChangeSlideComboTitle {
            get {
                return ResourceManager.GetString("ChangeSlideComboTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart Options 的本地化字符串。
        /// </summary>
        public static string ChartControlToolTip {
            get {
                return ResourceManager.GetString("ChartControlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose an entity 的本地化字符串。
        /// </summary>
        public static string ChooseAnEntityCaption {
            get {
                return ResourceManager.GetString("ChooseAnEntityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse operation is not successful due to circular ownership 的本地化字符串。
        /// </summary>
        public static string CollapseError {
            get {
                return ResourceManager.GetString("CollapseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in Collapse 的本地化字符串。
        /// </summary>
        public static string CollapseErrorTitle {
            get {
                return ResourceManager.GetString("CollapseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        public static string CollapseToolTip {
            get {
                return ResourceManager.GetString("CollapseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Picker 的本地化字符串。
        /// </summary>
        public static string ColorPickerToolTip {
            get {
                return ResourceManager.GetString("ColorPickerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Properties 的本地化字符串。
        /// </summary>
        public static string ColorPropertiesToolTip {
            get {
                return ResourceManager.GetString("ColorPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compact Tree Arc Layout 的本地化字符串。
        /// </summary>
        public static string CompactTreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("CompactTreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compact Tree Layout 的本地化字符串。
        /// </summary>
        public static string CompactTreeLayoutToolTip {
            get {
                return ResourceManager.GetString("CompactTreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create report comparing multiple slides. 的本地化字符串。
        /// </summary>
        public static string CompareReportToolTip {
            get {
                return ResourceManager.GetString("CompareReportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare Slides 的本地化字符串。
        /// </summary>
        public static string CompareSlideToolTip {
            get {
                return ResourceManager.GetString("CompareSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Entity Label 的本地化字符串。
        /// </summary>
        public static string ConfigureEntityLabelToolTip {
            get {
                return ResourceManager.GetString("ConfigureEntityLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete? 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2010 Orbitax. All right reserved. 的本地化字符串。
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corporate tax rate:  的本地化字符串。
        /// </summary>
        public static string CorporateTaxHeader {
            get {
                return ResourceManager.GetString("CorporateTaxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TME does not maintain income tax rates for individuals and unincorporated entities (a default rate equal to the rate that applies to corporations is assumed) and certain foreign countries (a default rate of 0% is assumed). Click here to edit this rate. 的本地化字符串。
        /// </summary>
        public static string CorporateTaxNonSupportedMessage {
            get {
                return ResourceManager.GetString("CorporateTaxNonSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the Find Corporate Rates button and choose entities to view their rates. 的本地化字符串。
        /// </summary>
        public static string CorporateTaxSubHeader {
            get {
                return ResourceManager.GetString("CorporateTaxSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corporation 的本地化字符串。
        /// </summary>
        public static string CorporationToolTip {
            get {
                return ResourceManager.GetString("CorporationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corporate Tax Rate 的本地化字符串。
        /// </summary>
        public static string CorpRatePrintHeader {
            get {
                return ResourceManager.GetString("CorpRatePrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withholding tax rate:  的本地化字符串。
        /// </summary>
        public static string CrossBorderTaxHeader {
            get {
                return ResourceManager.GetString("CrossBorderTaxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose The paying entity, one or more receiving countries, a payment stream, then click on the search button. 的本地化字符串。
        /// </summary>
        public static string CrossBorderTaxInputPanelText {
            get {
                return ResourceManager.GetString("CrossBorderTaxInputPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TME does not maintain withholding tax rates for transactions between domestic entities (a default rate of 0% is assumed), individuals and unincorporated entities (a default rate equal to the rate that applies to corporations is assumed) and certain foreign countries (a default rate of 0% is assumed). Click here to edit this rate. 的本地化字符串。
        /// </summary>
        public static string CrossBorderTaxNonSuportedToolTip {
            get {
                return ResourceManager.GetString("CrossBorderTaxNonSuportedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Find Withholding Rates button to choose paying entity, one or more receiving entity(ies) and payment stream for the withholding rates. 的本地化字符串。
        /// </summary>
        public static string CrossBorderTaxSubHeader {
            get {
                return ResourceManager.GetString("CrossBorderTaxSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corporate Structure Book 的本地化字符串。
        /// </summary>
        public static string CSBookDefaultFileName {
            get {
                return ResourceManager.GetString("CSBookDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CORPORATE STRUCTURE BOOK 的本地化字符串。
        /// </summary>
        public static string CSBookDefaultPageTitle {
            get {
                return ResourceManager.GetString("CSBookDefaultPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated CS Book 的本地化字符串。
        /// </summary>
        public static string CSBookFilterStartString {
            get {
                return ResourceManager.GetString("CSBookFilterStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create CS Book 的本地化字符串。
        /// </summary>
        public static string CSBookOpenSaveDialogTitle {
            get {
                return ResourceManager.GetString("CSBookOpenSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CTB must have a parent 的本地化字符串。
        /// </summary>
        public static string CTBMastHaveAParent {
            get {
                return ResourceManager.GetString("CTBMastHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CTB 的本地化字符串。
        /// </summary>
        public static string CTBToolTip {
            get {
                return ResourceManager.GetString("CTBToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply layout style for entire chart. 的本地化字符串。
        /// </summary>
        public static string CurrentLayoutToolTip {
            get {
                return ResourceManager.GetString("CurrentLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply layout style for children of selected parent. 的本地化字符串。
        /// </summary>
        public static string CurrentNodePlacerToolTip {
            get {
                return ResourceManager.GetString("CurrentNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column name cannot be empty 的本地化字符串。
        /// </summary>
        public static string CustomColumnEmptyMessage {
            get {
                return ResourceManager.GetString("CustomColumnEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same column name already exists 的本地化字符串。
        /// </summary>
        public static string CustomColumnExistingMessage {
            get {
                return ResourceManager.GetString("CustomColumnExistingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select or type your custom column name 的本地化字符串。
        /// </summary>
        public static string CustomColumnWindowText {
            get {
                return ResourceManager.GetString("CustomColumnWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please type your custom column name 的本地化字符串。
        /// </summary>
        public static string CustomColumnWindowTextForTaskAndRepository {
            get {
                return ResourceManager.GetString("CustomColumnWindowTextForTaskAndRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string CutToolTip {
            get {
                return ResourceManager.GetString("CutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Survey 的本地化字符串。
        /// </summary>
        public static string DataSurveyCancelSurveyButtonText {
            get {
                return ResourceManager.GetString("DataSurveyCancelSurveyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deselect 的本地化字符串。
        /// </summary>
        public static string DataSurveyContextMenuDeselectAllCells {
            get {
                return ResourceManager.GetString("DataSurveyContextMenuDeselectAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the entire sheet 的本地化字符串。
        /// </summary>
        public static string DataSurveyContextMenuSelectAllCells {
            get {
                return ResourceManager.GetString("DataSurveyContextMenuSelectAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string DataSurveyContextMenuSelectCells {
            get {
                return ResourceManager.GetString("DataSurveyContextMenuSelectCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue Survey 的本地化字符串。
        /// </summary>
        public static string DataSurveyContinueSurveyButtonText {
            get {
                return ResourceManager.GetString("DataSurveyContinueSurveyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some of your selection is outside the valid range for the TME survey. TME supports $A$1:$Z$200. 的本地化字符串。
        /// </summary>
        public static string DataSurveyMaxRowColumnExcededMessage {
            get {
                return ResourceManager.GetString("DataSurveyMaxRowColumnExcededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text properties cannot be altered here 的本地化字符串。
        /// </summary>
        public static string DesignerPreferenceTextStyleComment {
            get {
                return ResourceManager.GetString("DesignerPreferenceTextStyleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Designer Preferences 的本地化字符串。
        /// </summary>
        public static string DesignerPreferenceToolTip {
            get {
                return ResourceManager.GetString("DesignerPreferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disregarded must have a parent 的本地化字符串。
        /// </summary>
        public static string DisregardedMastHaveAParent {
            get {
                return ResourceManager.GetString("DisregardedMastHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disregarded 的本地化字符串。
        /// </summary>
        public static string DisregardedToolTip {
            get {
                return ResourceManager.GetString("DisregardedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string DoneButtonCaption {
            get {
                return ResourceManager.GetString("DoneButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double Align Left 的本地化字符串。
        /// </summary>
        public static string DoubleAlignLeftNodePlacerToolTip {
            get {
                return ResourceManager.GetString("DoubleAlignLeftNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double Side 的本地化字符串。
        /// </summary>
        public static string DoubleSideNodePlacerToolTip {
            get {
                return ResourceManager.GetString("DoubleSideNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ellipse 的本地化字符串。
        /// </summary>
        public static string EllipseToolTip {
            get {
                return ResourceManager.GetString("EllipseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the space below to set what shows up in the entity boxes. Add data elements that automatically fill up for that entity by clicking &quot;Insert Entity Data&quot; (these connected fields are highlighted in yellow), or put in your own. By editing the fields below you can also arrange the way the data is shown along with its formatting.  的本地化字符串。
        /// </summary>
        public static string EntityLabelConfiguratorDescription {
            get {
                return ResourceManager.GetString("EntityLabelConfiguratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show minimum information in the entity box to speed up the charting 的本地化字符串。
        /// </summary>
        public static string EntityLabelMode {
            get {
                return ResourceManager.GetString("EntityLabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name of an entity cannot be empty 的本地化字符串。
        /// </summary>
        public static string EntityNameErrorToolTip {
            get {
                return ResourceManager.GetString("EntityNameErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Short name of an entity cannot be empty 的本地化字符串。
        /// </summary>
        public static string EntityShortNameErrorToolTip {
            get {
                return ResourceManager.GetString("EntityShortNameErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation Required 的本地化字符串。
        /// </summary>
        public static string ErrorToolTipTitle {
            get {
                return ResourceManager.GetString("ErrorToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, TME has encountered an error. 的本地化字符串。
        /// </summary>
        public static string ExceptionHeaderText {
            get {
                return ResourceManager.GetString("ExceptionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View technical data 的本地化字符串。
        /// </summary>
        public static string ExceptionLabel1Text1 {
            get {
                return ResourceManager.GetString("ExceptionLabel1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide technical data 的本地化字符串。
        /// </summary>
        public static string ExceptionLabel1Text2 {
            get {
                return ResourceManager.GetString("ExceptionLabel1Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sent if you wish to report this problem 的本地化字符串。
        /// </summary>
        public static string ExceptionLabel2Text1 {
            get {
                return ResourceManager.GetString("ExceptionLabel2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        public static string ExceptionLabel2Text2 {
            get {
                return ResourceManager.GetString("ExceptionLabel2Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send feedback 的本地化字符串。
        /// </summary>
        public static string ExceptionSendButtonTextCompact {
            get {
                return ResourceManager.GetString("ExceptionSendButtonTextCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report this problem 的本地化字符串。
        /// </summary>
        public static string ExceptionSendButtonTextNormal {
            get {
                return ResourceManager.GetString("ExceptionSendButtonTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error in TME, please help us fix it by reporting this to us. 的本地化字符串。
        /// </summary>
        public static string ExceptionTitleText {
            get {
                return ResourceManager.GetString("ExceptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        public static string ExpandToolTip {
            get {
                return ResourceManager.GetString("ExpandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string ExportButtonCaption {
            get {
                return ResourceManager.GetString("ExportButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting spreadsheet please wait... 的本地化字符串。
        /// </summary>
        public static string ExportCommonWaitMsg {
            get {
                return ResourceManager.GetString("ExportCommonWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Doc 的本地化字符串。
        /// </summary>
        public static string ExportDocButtonCaption {
            get {
                return ResourceManager.GetString("ExportDocButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export just current slide 的本地化字符串。
        /// </summary>
        public static string ExportJustCurrenteSlide {
            get {
                return ResourceManager.GetString("ExportJustCurrenteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to PDF 的本地化字符串。
        /// </summary>
        public static string ExportPdfButtonCaption {
            get {
                return ResourceManager.GetString("ExportPdfButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string ExportTitleCaption {
            get {
                return ResourceManager.GetString("ExportTitleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office 2003 的本地化字符串。
        /// </summary>
        public static string ExportTo2003 {
            get {
                return ResourceManager.GetString("ExportTo2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office 2007 的本地化字符串。
        /// </summary>
        public static string ExportTo2007 {
            get {
                return ResourceManager.GetString("ExportTo2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Excel 的本地化字符串。
        /// </summary>
        public static string ExportToExcelCommonDialogTitle {
            get {
                return ResourceManager.GetString("ExportToExcelCommonDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file does not exist, or has been deleted 的本地化字符串。
        /// </summary>
        public static string FileOpeningFailedMessage {
            get {
                return ResourceManager.GetString("FileOpeningFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill Color 的本地化字符串。
        /// </summary>
        public static string FillColorToolTip {
            get {
                return ResourceManager.GetString("FillColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit Entity Size 的本地化字符串。
        /// </summary>
        public static string FitEntitySizeLabel {
            get {
                return ResourceManager.GetString("FitEntitySizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit Entity Size 的本地化字符串。
        /// </summary>
        public static string FitEntitySizeTooltip {
            get {
                return ResourceManager.GetString("FitEntitySizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size 的本地化字符串。
        /// </summary>
        public static string FontSizeTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("FontSizeTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Font 的本地化字符串。
        /// </summary>
        public static string FontStyleTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("FontStyleTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full-screen Off 的本地化字符串。
        /// </summary>
        public static string FullscreenModeOffTooltip {
            get {
                return ResourceManager.GetString("FullscreenModeOffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full-screen 的本地化字符串。
        /// </summary>
        public static string FullscreenModeOnTooltip {
            get {
                return ResourceManager.GetString("FullscreenModeOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Print Preview 的本地化字符串。
        /// </summary>
        public static string GeneratingPrintPreviewStatusMessage {
            get {
                return ResourceManager.GetString("GeneratingPrintPreviewStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET STARTED 的本地化字符串。
        /// </summary>
        public static string GetStartedButtonContent {
            get {
                return ResourceManager.GetString("GetStartedButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden Transaction(s) 的本地化字符串。
        /// </summary>
        public static string HiddenTransactionTitle {
            get {
                return ResourceManager.GetString("HiddenTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hierarchical Arc Layout 的本地化字符串。
        /// </summary>
        public static string HierarchicalArcLayoutToolTip {
            get {
                return ResourceManager.GetString("HierarchicalArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hierarchical Layout 的本地化字符串。
        /// </summary>
        public static string HierarchicalLayoutToolTip {
            get {
                return ResourceManager.GetString("HierarchicalLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WW Tax Calculator and Optimizer 的本地化字符串。
        /// </summary>
        public static string HomeAdvanceCalculatorHeader {
            get {
                return ResourceManager.GetString("HomeAdvanceCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculate worldwide tax for current and future years and analyze repatriation and tax minimization strategies. 的本地化字符串。
        /// </summary>
        public static string HomeAdvanceCalculatorText {
            get {
                return ResourceManager.GetString("HomeAdvanceCalculatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collaboration 的本地化字符串。
        /// </summary>
        public static string HomeCollaborationHeader {
            get {
                return ResourceManager.GetString("HomeCollaborationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Organize and store documents online, automatically collect data from around the world and keep track of tax returns and other due dates.  的本地化字符串。
        /// </summary>
        public static string HomeCollaborationText {
            get {
                return ResourceManager.GetString("HomeCollaborationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity Chart 的本地化字符串。
        /// </summary>
        public static string HomeEntityChart {
            get {
                return ResourceManager.GetString("HomeEntityChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visually build and maintain your entity chart. Create reports and presentations. 的本地化字符串。
        /// </summary>
        public static string HomeEntityChartPara {
            get {
                return ResourceManager.GetString("HomeEntityChartPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Research and Compliance 的本地化字符串。
        /// </summary>
        public static string HomeResearchandComplianceHeader {
            get {
                return ResourceManager.GetString("HomeResearchandComplianceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Tax Management Expert 的本地化字符串。
        /// </summary>
        public static string HomeWelComeHeader {
            get {
                return ResourceManager.GetString("HomeWelComeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tax Management Expert (TME) is your one-stop shop for all your tax management needs. Please visit www.orbitax.com for information about other international tax products and services by Orbitax. 的本地化字符串。
        /// </summary>
        public static string HomeWelComePara {
            get {
                return ResourceManager.GetString("HomeWelComePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HV Tree Arc Layout 的本地化字符串。
        /// </summary>
        public static string HorVertTreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("HorVertTreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HV Tree Layout 的本地化字符串。
        /// </summary>
        public static string HorVertTreeLayoutToolTip {
            get {
                return ResourceManager.GetString("HorVertTreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        public static string IgnoreButtonCaption {
            get {
                return ResourceManager.GetString("IgnoreButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string ImportButtonCaption {
            get {
                return ResourceManager.GetString("ImportButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The scenario hasn&apos;t been created with the current slide. Do you still want to import entities from current slide? 的本地化字符串。
        /// </summary>
        public static string ImportEntityChartIntoCalculatorConfirmationMessage {
            get {
                return ResourceManager.GetString("ImportEntityChartIntoCalculatorConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The scenario hasn&apos;t been created with the current slide. Do you still want to import transactions from current slide? 的本地化字符串。
        /// </summary>
        public static string ImportTransactionsIntoCalculatorConfirmationMessage {
            get {
                return ResourceManager.GetString("ImportTransactionsIntoCalculatorConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to see the slide contents 的本地化字符串。
        /// </summary>
        public static string InActiveSlideToolTip {
            get {
                return ResourceManager.GetString("InActiveSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Keyword 的本地化字符串。
        /// </summary>
        public static string InsertKeywordButtonToolTip {
            get {
                return ResourceManager.GetString("InsertKeywordButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not connected to internet. Please connect to internet and try again. 的本地化字符串。
        /// </summary>
        public static string InternetErrorDetail {
            get {
                return ResourceManager.GetString("InternetErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to connect to server 的本地化字符串。
        /// </summary>
        public static string InternetErrorHeader {
            get {
                return ResourceManager.GetString("InternetErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internet connection problem 的本地化字符串。
        /// </summary>
        public static string InternetErrorTitle {
            get {
                return ResourceManager.GetString("InternetErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch cannot have any child 的本地化字符串。
        /// </summary>
        public static string InvalidBranchChild {
            get {
                return ResourceManager.GetString("InvalidBranchChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch can have only one parent 的本地化字符串。
        /// </summary>
        public static string InvalidBranchParent {
            get {
                return ResourceManager.GetString("InvalidBranchParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disregarded can have only one parent 的本地化字符串。
        /// </summary>
        public static string InvalidDisregardedParent {
            get {
                return ResourceManager.GetString("InvalidDisregardedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide valid email to assign. Each Email addreses must be valid and less than 255 characters 的本地化字符串。
        /// </summary>
        public static string InvalidEmailAddressForAssignment {
            get {
                return ResourceManager.GetString("InvalidEmailAddressForAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide valid email to assign. Each Email addreses must be valid and less than 255 characters. Also Please select Excel cells. 的本地化字符串。
        /// </summary>
        public static string InvalidEmailAddressOrCellsForAssignmen {
            get {
                return ResourceManager.GetString("InvalidEmailAddressOrCellsForAssignmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email address is not valid 的本地化字符串。
        /// </summary>
        public static string InvalidEmainAddressErrorToolTip {
            get {
                return ResourceManager.GetString("InvalidEmainAddressErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving percentage not 100% 的本地化字符串。
        /// </summary>
        public static string InvalidLiquidatePercentage {
            get {
                return ResourceManager.GetString("InvalidLiquidatePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting entity cannot be a parent or child of any entity 的本地化字符串。
        /// </summary>
        public static string InvalidOwnershipForDeletingEntity {
            get {
                return ResourceManager.GetString("InvalidOwnershipForDeletingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partnership must have minimum two parents 的本地化字符串。
        /// </summary>
        public static string InvalidPartnership {
            get {
                return ResourceManager.GetString("InvalidPartnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RCTB must have minimum two parents 的本地化字符串。
        /// </summary>
        public static string InvalidRCTB {
            get {
                return ResourceManager.GetString("InvalidRCTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Third-party entity cannot own 100% 的本地化字符串。
        /// </summary>
        public static string InvalidThirdpartyOwnership {
            get {
                return ResourceManager.GetString("InvalidThirdpartyOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        public static string ItalicToolTip {
            get {
                return ResourceManager.GetString("ItalicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layouting all slides to {0} 的本地化字符串。
        /// </summary>
        public static string LayoutAllSlideMessage {
            get {
                return ResourceManager.GetString("LayoutAllSlideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout Slides 的本地化字符串。
        /// </summary>
        public static string LayoutAllSlideProgressTitle {
            get {
                return ResourceManager.GetString("LayoutAllSlideProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        public static string LegendToolTip {
            get {
                return ResourceManager.GetString("LegendToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dot Dot Dash 的本地化字符串。
        /// </summary>
        public static string LinePatternDashDotDot {
            get {
                return ResourceManager.GetString("LinePatternDashDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dot Dash Dash 的本地化字符串。
        /// </summary>
        public static string LinePatternDashDotDotDot {
            get {
                return ResourceManager.GetString("LinePatternDashDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dot Dash 的本地化字符串。
        /// </summary>
        public static string LinePatternDashDotToolTip {
            get {
                return ResourceManager.GetString("LinePatternDashDotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashed 的本地化字符串。
        /// </summary>
        public static string LinePatternDashedToolTip {
            get {
                return ResourceManager.GetString("LinePatternDashedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dotted 的本地化字符串。
        /// </summary>
        public static string LinePatternDottedToolTip {
            get {
                return ResourceManager.GetString("LinePatternDottedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid 的本地化字符串。
        /// </summary>
        public static string LinePatternSolidToolTip {
            get {
                return ResourceManager.GetString("LinePatternSolidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line Properties 的本地化字符串。
        /// </summary>
        public static string LinePropertiesToolTip {
            get {
                return ResourceManager.GetString("LinePropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        public static string LineToolTip {
            get {
                return ResourceManager.GetString("LineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 1 的本地化字符串。
        /// </summary>
        public static string LineWidth1ToolTip {
            get {
                return ResourceManager.GetString("LineWidth1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 2 的本地化字符串。
        /// </summary>
        public static string LineWidth2ToolTip {
            get {
                return ResourceManager.GetString("LineWidth2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 3 的本地化字符串。
        /// </summary>
        public static string LineWidth3ToolTip {
            get {
                return ResourceManager.GetString("LineWidth3ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 4 的本地化字符串。
        /// </summary>
        public static string LineWidth4ToolTip {
            get {
                return ResourceManager.GetString("LineWidth4ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 5 的本地化字符串。
        /// </summary>
        public static string LineWidth5ToolTip {
            get {
                return ResourceManager.GetString("LineWidth5ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 6 的本地化字符串。
        /// </summary>
        public static string LineWidth6ToolTip {
            get {
                return ResourceManager.GetString("LineWidth6ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magnifier 的本地化字符串。
        /// </summary>
        public static string MagnifyToolTip {
            get {
                return ResourceManager.GetString("MagnifyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Same Height 的本地化字符串。
        /// </summary>
        public static string MakeSameHeightToolTip {
            get {
                return ResourceManager.GetString("MakeSameHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Same Height-Width 的本地化字符串。
        /// </summary>
        public static string MakeSameSizeBothToolTip {
            get {
                return ResourceManager.GetString("MakeSameSizeBothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Same Size 的本地化字符串。
        /// </summary>
        public static string MakeSameSizeToolTip {
            get {
                return ResourceManager.GetString("MakeSameSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Same Width 的本地化字符串。
        /// </summary>
        public static string MakeSameWidthToolTip {
            get {
                return ResourceManager.GetString("MakeSameWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        public static string NavigationToolTip {
            get {
                return ResourceManager.GetString("NavigationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentage cannot be negative 的本地化字符串。
        /// </summary>
        public static string NegativePercentageError {
            get {
                return ResourceManager.GetString("NegativePercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New entity must have a parent 的本地化字符串。
        /// </summary>
        public static string NewEntityMustHaveAParent {
            get {
                return ResourceManager.GetString("NewEntityMustHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string NoButtonCaption {
            get {
                return ResourceManager.GetString("NoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This country&apos;s tax rates are not currently maintained in the TME database 的本地化字符串。
        /// </summary>
        public static string NonSuportedCountryToolTip {
            get {
                return ResourceManager.GetString("NonSuportedCountryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        public static string NoteToolTip {
            get {
                return ResourceManager.GetString("NoteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OkButtonCaption {
            get {
                return ResourceManager.GetString("OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Online Share&gt;  的本地化字符串。
        /// </summary>
        public static string OnlineRepositoryLinkTooltipPrefix {
            get {
                return ResourceManager.GetString("OnlineRepositoryLinkTooltipPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string OpenButtonCaption {
            get {
                return ResourceManager.GetString("OpenButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        public static string OrCaption {
            get {
                return ResourceManager.GetString("OrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orthogonal Arc Layout 的本地化字符串。
        /// </summary>
        public static string OrthogonalArcLayoutToolTip {
            get {
                return ResourceManager.GetString("OrthogonalArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orthogonal Layout 的本地化字符串。
        /// </summary>
        public static string OrthogonalLayoutToolTip {
            get {
                return ResourceManager.GetString("OrthogonalLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentage cannot be greater than 100 的本地化字符串。
        /// </summary>
        public static string OverflowPercentageError {
            get {
                return ResourceManager.GetString("OverflowPercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The total holding percentage cannot be greater than 100 的本地化字符串。
        /// </summary>
        public static string OwnershipPercentageGeaterThan100 {
            get {
                return ResourceManager.GetString("OwnershipPercentageGeaterThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The total holding percentage cannot be less than 100 的本地化字符串。
        /// </summary>
        public static string OwnershipPercentageLessThan100 {
            get {
                return ResourceManager.GetString("OwnershipPercentageLessThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} owns {1}% of {2} 的本地化字符串。
        /// </summary>
        public static string OwnershipToolTip {
            get {
                return ResourceManager.GetString("OwnershipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partnership or Trust 的本地化字符串。
        /// </summary>
        public static string PartnershipToolTip {
            get {
                return ResourceManager.GetString("PartnershipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pen 的本地化字符串。
        /// </summary>
        public static string PenToolTip {
            get {
                return ResourceManager.GetString("PenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon 的本地化字符串。
        /// </summary>
        public static string PolygonToolTip {
            get {
                return ResourceManager.GetString("PolygonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string PrintButtonCaption {
            get {
                return ResourceManager.GetString("PrintButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Selected Printer Is In Error 的本地化字符串。
        /// </summary>
        public static string PrinterErrorToolTip {
            get {
                return ResourceManager.GetString("PrinterErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report produced by Tax Management Expert (TME). www.orbitax.com 的本地化字符串。
        /// </summary>
        public static string PrintFooterText {
            get {
                return ResourceManager.GetString("PrintFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string PrintSelectionDialogTitle {
            get {
                return ResourceManager.GetString("PrintSelectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cell is not editable. 的本地化字符串。
        /// </summary>
        public static string ProtectedCellEditError {
            get {
                return ResourceManager.GetString("ProtectedCellEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1}, WHT: {2} 的本地化字符串。
        /// </summary>
        public static string PTToolTip {
            get {
                return ResourceManager.GetString("PTToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RCTB 的本地化字符串。
        /// </summary>
        public static string RCTBToolTip {
            get {
                return ResourceManager.GetString("RCTBToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rectangle 的本地化字符串。
        /// </summary>
        public static string RectangleToolTip {
            get {
                return ResourceManager.GetString("RectangleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The scenario hasn&apos;t been created with the current slide. Do you want to refresh with current slide? 的本地化字符串。
        /// </summary>
        public static string RefreshCalculatorScenerioConfirmationMessage {
            get {
                return ResourceManager.GetString("RefreshCalculatorScenerioConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Slide 的本地化字符串。
        /// </summary>
        public static string RemoveSlideToolTip {
            get {
                return ResourceManager.GetString("RemoveSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository 的本地化字符串。
        /// </summary>
        public static string RepositoryHeader {
            get {
                return ResourceManager.GetString("RepositoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository 的本地化字符串。
        /// </summary>
        public static string RepositoryPrintHeader {
            get {
                return ResourceManager.GetString("RepositoryPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create, delete and modify your attachments. 的本地化字符串。
        /// </summary>
        public static string RepositorySubHeader {
            get {
                return ResourceManager.GetString("RepositorySubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column name is reserved 的本地化字符串。
        /// </summary>
        public static string ReservedComunNameErrorMessage {
            get {
                return ResourceManager.GetString("ReservedComunNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrease Size 的本地化字符串。
        /// </summary>
        public static string ResizeDecreaseSizeToolTip {
            get {
                return ResourceManager.GetString("ResizeDecreaseSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize chart to fit slide 的本地化字符串。
        /// </summary>
        public static string ResizeExportedChartToFitSlide {
            get {
                return ResourceManager.GetString("ResizeExportedChartToFitSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase Size 的本地化字符串。
        /// </summary>
        public static string ResizeIncreaseSizeToolTip {
            get {
                return ResourceManager.GetString("ResizeIncreaseSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string RetryButtonCaption {
            get {
                return ResourceManager.GetString("RetryButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule details 的本地化字符串。
        /// </summary>
        public static string RuleDetailsPrintRadioText {
            get {
                return ResourceManager.GetString("RuleDetailsPrintRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule summaries 的本地化字符串。
        /// </summary>
        public static string RuleSummaryPrintRadioText {
            get {
                return ResourceManager.GetString("RuleSummaryPrintRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveButtonCaption {
            get {
                return ResourceManager.GetString("SaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save project 的本地化字符串。
        /// </summary>
        public static string SaveConfirmHeader {
            get {
                return ResourceManager.GetString("SaveConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have unsaved data, do you want to save project? 的本地化字符串。
        /// </summary>
        public static string SaveConfirmMessage {
            get {
                return ResourceManager.GetString("SaveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survey has saved as template. 的本地化字符串。
        /// </summary>
        public static string SaveSurveyAsTemplateMessage {
            get {
                return ResourceManager.GetString("SaveSurveyAsTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Next 的本地化字符串。
        /// </summary>
        public static string SearchNextToolTip {
            get {
                return ResourceManager.GetString("SearchNextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No match 的本地化字符串。
        /// </summary>
        public static string SearchNoMatch {
            get {
                return ResourceManager.GetString("SearchNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show search option 的本地化字符串。
        /// </summary>
        public static string SearchOptionCollapsedButtonCaption {
            get {
                return ResourceManager.GetString("SearchOptionCollapsedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide search option 的本地化字符串。
        /// </summary>
        public static string SearchOptionExpandedButtonCaption {
            get {
                return ResourceManager.GetString("SearchOptionExpandedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search option 的本地化字符串。
        /// </summary>
        public static string SearchOptionExpanderHeader {
            get {
                return ResourceManager.GetString("SearchOptionExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Previous 的本地化字符串。
        /// </summary>
        public static string SearchPreviousToolTip {
            get {
                return ResourceManager.GetString("SearchPreviousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show search result 的本地化字符串。
        /// </summary>
        public static string SearchResultCollapsedButtonCaption {
            get {
                return ResourceManager.GetString("SearchResultCollapsedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide search result 的本地化字符串。
        /// </summary>
        public static string SearchResultExpandedButtonCaption {
            get {
                return ResourceManager.GetString("SearchResultExpandedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search result 的本地化字符串。
        /// </summary>
        public static string SearchResultHeader {
            get {
                return ResourceManager.GetString("SearchResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string SearchToolTip {
            get {
                return ResourceManager.GetString("SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string SelectAllToolTip {
            get {
                return ResourceManager.GetString("SelectAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select layout style for entire chart. 的本地化字符串。
        /// </summary>
        public static string SelectLayoutToolTip {
            get {
                return ResourceManager.GetString("SelectLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select layout style for children of selected parent. 的本地化字符串。
        /// </summary>
        public static string SelectNodePlacerToolTip {
            get {
                return ResourceManager.GetString("SelectNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as default 的本地化字符串。
        /// </summary>
        public static string SetAsDefaultButtonCaption {
            get {
                return ResourceManager.GetString("SetAsDefaultButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Problem connecting to online share, TME will start without the collaboration feature now. 的本地化字符串。
        /// </summary>
        public static string SharepointServerNotFound {
            get {
                return ResourceManager.GetString("SharepointServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Payment Transactions 的本地化字符串。
        /// </summary>
        public static string ShowHidePTToolTip {
            get {
                return ResourceManager.GetString("ShowHidePTToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing Transaction(s) 的本地化字符串。
        /// </summary>
        public static string ShowingTransactionTitle {
            get {
                return ResourceManager.GetString("ShowingTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Top 的本地化字符串。
        /// </summary>
        public static string SingleTopNodePlacerToolTip {
            get {
                return ResourceManager.GetString("SingleTopNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to edit slide title. 的本地化字符串。
        /// </summary>
        public static string SlideLabelToolTip {
            get {
                return ResourceManager.GetString("SlideLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Slide for All Tabs 的本地化字符串。
        /// </summary>
        public static string SlideSelectorHeading {
            get {
                return ResourceManager.GetString("SlideSelectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth Polygon 的本地化字符串。
        /// </summary>
        public static string SmoothPolygonToolTip {
            get {
                return ResourceManager.GetString("SmoothPolygonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort slides 的本地化字符串。
        /// </summary>
        public static string SortSlidesToolTip {
            get {
                return ResourceManager.GetString("SortSlidesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + Add Item 的本地化字符串。
        /// </summary>
        public static string SplitedNumberEditorAddItem {
            get {
                return ResourceManager.GetString("SplitedNumberEditorAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity Data 的本地化字符串。
        /// </summary>
        public static string SSTPrintHeader {
            get {
                return ResourceManager.GetString("SSTPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stagger 的本地化字符串。
        /// </summary>
        public static string StaggerNodePlacerToolTip {
            get {
                return ResourceManager.GetString("StaggerNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survey record will be deleted. To delete associated files and folders please delete from repository. 的本地化字符串。
        /// </summary>
        public static string SurveyDeleteConfirmMsg {
            get {
                return ResourceManager.GetString("SurveyDeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to cancel the survey? 的本地化字符串。
        /// </summary>
        public static string SurveyEditorCloseConfirmMessage {
            get {
                return ResourceManager.GetString("SurveyEditorCloseConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Survey 的本地化字符串。
        /// </summary>
        public static string SurveyEditorCloseConfirmTitle {
            get {
                return ResourceManager.GetString("SurveyEditorCloseConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survey Templete record will be deleted. To delete associated files and folders please delete from repository 的本地化字符串。
        /// </summary>
        public static string SurveyTemplateDeleteConfirmMsg {
            get {
                return ResourceManager.GetString("SurveyTemplateDeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting spreadsheet please wait... 的本地化字符串。
        /// </summary>
        public static string TaskExportWaitMsg {
            get {
                return ResourceManager.GetString("TaskExportWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Manager 的本地化字符串。
        /// </summary>
        public static string TaskHeader {
            get {
                return ResourceManager.GetString("TaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task manager 的本地化字符串。
        /// </summary>
        public static string TaskManagerPrintHeader {
            get {
                return ResourceManager.GetString("TaskManagerPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create, delete and modify your tasks. 的本地化字符串。
        /// </summary>
        public static string TaskSubHeader {
            get {
                return ResourceManager.GetString("TaskSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assuming you can make an intercompany payment, select the payment stream and the receiving entity 的本地化字符串。
        /// </summary>
        public static string TCInterCompanyPaymentLabel {
            get {
                return ResourceManager.GetString("TCInterCompanyPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Properties 的本地化字符串。
        /// </summary>
        public static string TextPropertiesToolTip {
            get {
                return ResourceManager.GetString("TextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A third party cannot be owned by another entity 的本地化字符串。
        /// </summary>
        public static string ThirdPartyCannotBeOwnedByOthers {
            get {
                return ResourceManager.GetString("ThirdPartyCannotBeOwnedByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Third Party 的本地化字符串。
        /// </summary>
        public static string ThirdPartyToolTip {
            get {
                return ResourceManager.GetString("ThirdPartyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tree Arc Layout 的本地化字符串。
        /// </summary>
        public static string TreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("TreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tree Layout 的本地化字符串。
        /// </summary>
        public static string TreeLayoutToolTip {
            get {
                return ResourceManager.GetString("TreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the space below to set what shows up in the entity boxes. Add data elements that automatically fill up for that entity by clicking &quot;Insert Entity Data&quot; (these connected fields are highlighted in yellow), or put in your own. By editing the fields below you can also arrange the way the data is shown along with its formatting.  的本地化字符串。
        /// </summary>
        public static string TSSTLabelConfiguratorDescription {
            get {
                return ResourceManager.GetString("TSSTLabelConfiguratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underlined 的本地化字符串。
        /// </summary>
        public static string UnderlinedToolTip {
            get {
                return ResourceManager.GetString("UnderlinedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait... 的本地化字符串。
        /// </summary>
        public static string WaitScreenMessage {
            get {
                return ResourceManager.GetString("WaitScreenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withholding Tax Rate 的本地化字符串。
        /// </summary>
        public static string WithHoldingPrintHeader {
            get {
                return ResourceManager.GetString("WithHoldingPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Withholding tax rate details for {0} paying {1} 的本地化字符串。
        /// </summary>
        public static string WithHoldingRateDetailText {
            get {
                return ResourceManager.GetString("WithHoldingRateDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string YesButtonCaption {
            get {
                return ResourceManager.GetString("YesButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string ZoomControlToolTip {
            get {
                return ResourceManager.GetString("ZoomControlToolTip", resourceCulture);
            }
        }
    }
}
